vulnerabilities: []
misconfigurations:
  - id: DS-0026
    statement: health check is managed by compose or orchestrator
  - id: DS-0002
    paths:
      - runner/Dockerfile
    statement: runner executes user commands and requires root
  - id: DS-0002
    paths:
      - presenter/Dockerfile
    statement: presenter Dockerfile has no runtime image as Lambda uses bootstrap binary directly
