services:
  nginx:
    image: nginx:1.29.6-alpine
    profiles:
      - nginx
      - integration
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/errors.conf:/etc/nginx/errors.conf:ro

  broker:
    build: broker/
    ports:
      - "${BROKER_PORT}:8080"
    env_file:
      - broker/.env.example
    depends_on:
      dynamodb-init:
        condition: service_completed_successfully
    profiles:
      - broker
      - integration

  broker-test:
    build:
      context: broker/
      target: test-integration
    env_file:
      - broker/.env.example
    depends_on:
      dynamodb-init:
        condition: service_completed_successfully
    profiles:
      - test

  front:
    build:
      context: front/
      target: dev
    ports:
      - "${FRONT_PORT}:5173"
    volumes:
      - ./front/src:/app/src:ro
      - ./front/index.html:/app/index.html:ro
      - ./front/vite.config.ts:/app/vite.config.ts:ro
    environment:
      VITE_API_TARGET: http://nginx
    profiles:
      - front

  runner:
    build: runner/
    env_file:
      - runner/.env.example
    profiles:
      - runner
      - integration

  dynamodb-init:
    image: amazon/aws-cli:2.34.14@sha256:0a8bbdb160cbb09e357ba24533204e90a97e2e56beadf1730739644c2d5f1bdb
    entrypoint: ["sh", "/init/create-table.sh"]
    volumes:
      - ./init/create-table.sh:/init/create-table.sh:ro
    env_file:
      - broker/.env.example
    depends_on:
      dynamodb-local:
        condition: service_healthy
    profiles:
      - broker
      - test
      - integration

  dynamodb-local:
    image: amazon/dynamodb-local:3.3.0@sha256:d89f8fcc6b1a39cb35976c248ed42a28c66ae00dc043099210f5571e42648ab4
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "echo > /dev/tcp/localhost/8000"]
      interval: 5s
      timeout: 5s
      retries: 3
    profiles:
      - broker
      - test
      - integration

  integration-test:
    build: integration/
    environment:
      NGINX_URL: "http://nginx"
      BROKER_URL: "http://broker:8080"
    depends_on:
      - nginx
      - broker
      - runner
    profiles:
      - integration
