services:
  nginx:
    image: nginx:1.29.6-alpine
    profiles:
      - nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/errors.conf:/etc/nginx/errors.conf:ro

  broker:
    build: broker/
    ports:
      - "${BROKER_PORT}:8080"
    env_file:
      - broker/.env.example
    depends_on:
      dynamodb-local:
        condition: service_healthy
    profiles:
      - broker

  broker-test:
    build:
      context: broker/
      target: test-integration
    env_file:
      - broker/.env.example
    depends_on:
      dynamodb-local:
        condition: service_healthy
    profiles:
      - test

  front:
    build:
      context: front/
      target: dev
    ports:
      - "${FRONT_PORT}:5173"
    volumes:
      - ./front/src:/app/src:ro
      - ./front/index.html:/app/index.html:ro
      - ./front/vite.config.ts:/app/vite.config.ts:ro
    profiles:
      - front

  runner:
    build: runner/
    env_file:
      - runner/.env.example
    profiles:
      - runner

  dynamodb-local:
    image: amazon/dynamodb-local:3.3.0
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "echo > /dev/tcp/localhost/8000"]
      interval: 5s
      timeout: 5s
      retries: 3
    profiles:
      - broker
      - test
