worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;

        resolver 127.0.0.11 valid=10s;

        location /health {
            access_log off;
            default_type text/plain;
            return 200 'OK';
        }

        location = /_resolve {
            internal;
            set $broker_upstream http://broker:8080;
            proxy_pass $broker_upstream/resolve;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Cookie $http_cookie;
        }
    }
}
