name: Nginx

on:
  push:
    paths:
      - "nginx/**"

permissions:
  contents: read

jobs:
  nginx-config-test:
    runs-on: ubuntu-latest
    container:
      image: nginx:1.29.6-alpine
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Copy config and test
        run: |
          cp nginx/nginx.conf /etc/nginx/nginx.conf
          nginx -t
